
import static java.lang.String.valueOf;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alejandro
 */
public class Formularios3 extends javax.swing.JFrame {

    /**
     * Creates new form Formularios3
     */
    public Formularios3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(536, 697));
        getContentPane().setLayout(null);

        jLabel1.setText("Rut");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 290, 42, 26);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 330, 52, 22);

        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 380, 37, 14);

        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 430, 56, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 270, 280, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 320, 280, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(170, 370, 280, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(170, 420, 280, 30);

        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 560, 110, 50);

        jButton2.setText("Registrar");
        jButton2.setEnabled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 490, 110, 50);

        jButton3.setText("Borrar");
        jButton3.setEnabled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(50, 560, 110, 50);

        jButton4.setText("Modificar");
        jButton4.setEnabled(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(200, 490, 110, 50);

        jButton5.setText("Limpiar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(350, 490, 110, 50);

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 25)); // NOI18N
        jLabel5.setText("Registro Administrador ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 20, 420, 49);

        jButton6.setText("Volver");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(350, 560, 110, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yoana Medel interfaz 1.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 60, 220, 210);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a2.PNG"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 510, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection c = null;

        Statement stmt = null;

        String r, n, a, d;

        try {

            Class.forName("org.postgresql.Driver");

            c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/ejemplo", "postgres", "123456");

            stmt = c.createStatement();

            r = jTextField1.getText();
            n = jTextField2.getText();
            a = jTextField3.getText();
            d = jTextField4.getText();

            String sql = "INSERT INTO persona VALUES ('" + r + "', '" + n + "', '" + a + "', '" + d + "')";
           System.out.println(sql);
           
            stmt.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(null, "Datos Almacenados Satisfactoriamente");
            
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            
            stmt.close();
            //c.commit();
            c.close();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error al conectarse con la bdd\nSus datos NO han sido Almacenados");

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Connection c = null;

        Statement stmt = null;

        String r, n, a, d;

        try {

            Class.forName("org.postgresql.Driver");

            c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/ejemplo", "postgres", "123456");

            stmt = c.createStatement();

            r = jTextField1.getText();
            n = jTextField2.getText();
            a = jTextField3.getText();
            d = jTextField4.getText();

            String sql = "DELETE FROM persona WHERE rut ='" + jTextField1.getText() + "'";
            System.out.println(sql);
            
            stmt.executeUpdate(sql);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Datos Borrados Satisfactoriamente ");

            stmt.close();
            //c.commit();
            c.close();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error al conectarse con la bdd\nSus datos NO han sido Borrados");
            
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Connection c = null;

        Statement stmt = null;

        String r, n, a, d;

        try {

            Class.forName("org.postgresql.Driver");

            c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/ejemplo", "postgres", "123456");

            stmt = c.createStatement();

            r = jTextField1.getText();
            n = jTextField2.getText();
            a = jTextField3.getText();
            d = jTextField4.getText(); 

            String sql = "UPDATE persona SET nombre= '" +jTextField2.getText()+"', apellido='"+jTextField3.getText()+ "', edad='"+jTextField4.getText() 
                    + "' WHERE rut= '"+jTextField1.getText()+"'";
            System.out.println(sql);
            
            stmt.executeUpdate(sql);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Datos Modificados Satisfactoriamente ");
                       
            stmt.close();
             //c.commit();
            c.close();
            
        

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error al conectarse con la bdd\nSus datos NO han sido Modificados");
                           
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       jButton3.setEnabled(false);
       jButton4.setEnabled(false);
       jTextField1.setText("");
       jTextField2.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
            
       JOptionPane.showMessageDialog(null, "Datos Limpados Satisfactoriamente ");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Connection c = null;

        Statement stmt = null;

        String consulta;

        try {
            Class.forName("org.postgresql.Driver");

            c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/ejemplo", "postgres", "123456");
            stmt = c.createStatement();
            consulta = "select * from persona where rut='"+ jTextField1.getText() + "'";
            System.out.println(consulta);
            ResultSet rs = stmt.executeQuery(consulta);

            if (rs.next()) {

                String r = rs.getString("rut");
                String n = rs.getString("nombre");
                String a = rs.getString("apellido");
                int d = rs.getInt("edad");

                jTextField1.setText(r.trim());
                jTextField2.setText(n.trim());
                jTextField3.setText(a.trim());
                jTextField4.setText(valueOf(d).trim());

                jButton3.setEnabled(true);
                jButton4.setEnabled(true);

                //System.out.println("rut : "+ r + " Nombre :" + n + " Apellido :" + a + "Edad :" + d);

            } else {
                JOptionPane.showMessageDialog(null, "Rut no encontadro");
                jButton2.setEnabled(true);

            }

            rs.close();

            stmt.close();

            //c.commit();
            c.close();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error al conectarse con la bdd");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
       
          inicio formulario3 = new inicio();
        formulario3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formularios3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formularios3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formularios3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formularios3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formularios3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
